spring:
    datasource:
        url: jdbc:h2:mem:testdb;
        driverClassName: org.h2.Driver
        username: admin
        password: admin

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        
    security:
        user:  
            name: admin
            password: admin

    h2:
        console.enabled: true
