spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        
    security:
        user:  
            name: admin
            password: admin

    h2:
        console.enabled: true

server: 
    port: 0