spring:
    datasource:
        initialization-mode: always
        url: jdbc:h2:file:./server/src/galactic_database;
        driverClassName: org.h2.Driver
        username: admin
        password: admin
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
    
    flyway:
        enabled: true
        locations: classpath:db/migration

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        
    security:
        user:  
            name: admin
            password: admin

